import = ["~/.config/alacritty/theme.toml"]

[font]
builtin_box_drawing = true
size = 9.0

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Space", mods = "Control|Shift", action = "None" },
    { key = "F", mods = "Control|Shift", action = "None" },
    { key = "B", mods = "Control|Shift", action = "None" },
    { key = "L", mods = "Control", action = "None" },
]

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = -1


[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
# binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`¬]+"
