#!/bin/bash

action=$1

if [[ $action == set ]]; then
    wid=${4:-$(pfw)}
    xprop -id $wid -f $2 8i -set $2 $3
elif [[ $action == get ]]; then
    wid=${3:-$(pfw)}
    default=${4:-0}
    val=$(xprop -id $wid $2 | sed 's/.* = //')
    if [[ $val =~ [0-9]+ ]]; then
        echo $val
    else
        echo $default
    fi
fi
