# vim:ft=sh
# ~/.bashrc
#

if [ -z "$_HOME_DOT_PROFILE_INCLUDED" ]; then
    source ~/.profile
fi

# Only continue for interactive shells
[[ $- != *i* ]] && return

# Disable special handing of <c-s> and <c-q>
stty -ixon -ixoff

if [[ $(ps --no-header --pid=$PPID --format=comm) != "zsh" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} ]]
then
	shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
	exec zsh $LOGIN_OPTION
	exit $?
fi

complete -cf sudo

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Enable history appending instead of overwriting.  #139609
shopt -s histappend
HISTSIZE=10000
HISTFILESIZE=10000
HISTCONTROL=ignoreboth:erasedups
# reedit a history substitution line if it failed
shopt -s histreedit
# edit a recalled history line before executing
shopt -s histverify
# Append to history after each command. Fucks up `!number` history expansion
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Extended globs for more globbing goodness
shopt -s extglob
shopt -s expand_aliases

# xhost to allow remote X connections
# xhost +local:root > /dev/null 2>&1

[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

# Configuration
source ~/.config/bash/aliases.sh
source ~/.config/bash/git.sh

source <(starship init bash)
source <(zoxide init bash)
source <(COMPLETE=bash jj)

# Enhanced file path completion in bash - https://github.com/sio/bash-complete-partial-path
if [ -s "$HOME/.config/bash-complete-partial-path/bash_completion" ]
then
  source "$HOME/.config/bash-complete-partial-path/bash_completion"
  _bcpp --defaults
fi
