# vim:ft=sh
# ~/.bashrc
#

[[ $- != *i* ]] && return

[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

export TMPDIR="/tmp"

complete -cf sudo

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Enable history appending instead of overwriting.  #139609
shopt -s histappend
HISTSIZE=10000
HISTFILESIZE=10000
HISTCONTROL=ignoreboth:erasedups
# reedit a history substitution line if it failed
shopt -s histreedit
# edit a recalled history line before executing
shopt -s histverify
# Append to history after each command. Fucks up `!number` history expansion
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Extended globs for more globbing goodness
shopt -s extglob
shopt -s expand_aliases

# Disable special handing of <c-s> and <c-q>
stty -ixon -ixoff

# xhost to allow remote X connections
# xhost +local:root > /dev/null 2>&1

# Configuration
source ~/.config/bash/aliases.sh
source ~/.config/bash/git.sh

# Node Version Manager
test -r /usr/share/nvm/init-nvm.sh && source /usr/share/nvm/init-nvm.sh

# Opam: Ocaml package manager
command -v opam &> /dev/null && eval $(opam config env)

# Starship prompt
eval "$(starship init bash)"

# https://github.com/ajeetdsouza/zoxide
eval "$(zoxide init bash)"

# Enhanced file path completion in bash - https://github.com/sio/bash-complete-partial-path
if [ -s "$HOME/.config/bash-complete-partial-path/bash_completion" ]
then
  source "$HOME/.config/bash-complete-partial-path/bash_completion"
  _bcpp --defaults
fi

if [ -z "$_HOME_DOT_PROFILE_INCLUDED" ]; then
    source ~/.profile
fi

