# vim: ft=sh

if [ -z "$_HOME_DOT_PROFILE_INCLUDED" ]; then
    source ~/.profile
fi

fpath=(/usr/share/zsh-antidote/functions $fpath)
autoload -Uz antidote

zsh_plugins=${ZDOTDIR:-$HOME}/.zsh_plugins
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
    antidote bundle <${zsh_plugins}.txt >${zsh_plugins}.zsh
fi
source ${zsh_plugins}.zsh

[[ -v terminfo ]] || zmodload zsh/terminfo

if [[ -n "$terminfo[kcuu1]" ]]; then
  bindkey -M emacs "$terminfo[kcuu1]" history-substring-search-up
  bindkey -M viins "$terminfo[kcuu1]" history-substring-search-up
fi
if [[ -n "$terminfo[kcud1]" ]]; then
  bindkey -M emacs "$terminfo[kcud1]" history-substring-search-down
  bindkey -M viins "$terminfo[kcud1]" history-substring-search-down
fi

# Source additional local files if they exist.
source ~/.config/zsh/config.d/krc-aliases.zsh
source ~/.config/zsh/config.d/aliases.zsh
source ~/.config/zsh/config.d/git.zsh

# Autoload functions.
autoload -Uz zmv

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots     # no special treatment for file names with a leading dot
# setopt no_auto_menu  # require an extra TAB press to open the completion menu
setopt no_extended_glob # extended glob syntax often breaks git commands

iscmd() {
    which $1 > /dev/null
}

iscmd zoxide && source <(zoxide init zsh)
iscmd kubectl && source <(kubectl completion zsh)
iscmd himalaya && source <(himalaya completion zsh)
iscmd jj && source <(COMPLETE=zsh jj)

[[ -e /opt/google-cloud-sdk/path.zsh.inc ]] && source /opt/google-cloud-sdk/path.zsh.inc
[[ -e /opt/google-cloud-sdk/completion.zsh.inc ]] && source /opt/google-cloud-sdk/completion.zsh.inc

iscmd starship && source <(starship init zsh)
iscmd atuin && source <(atuin init zsh --disable-up-arrow)
