# syntax=docker/dockerfile:1.3-labs
FROM quay.io/toolbx/arch-toolbox:latest

RUN pacman -Sy --noconfirm glibc glibc-locales
# Update locale
RUN cat /etc/locale.gen
RUN echo "en_DK.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen

# Update package repository
RUN pacman -Syu --noconfirm

# Install dev tools
RUN xargs pacman -S --noconfirm <<EOF
    git
    base-devel
    dash
    zsh
    zoxide
    starship
    atuin
    diff-so-fancy
    bat
    eza
    ripgrep
    fd
    libqalculate
    bc
    jq
    bat
    fzf
    wl-clipboard
    lazygit
    kubectl
    rustup
    rsync
    man-db
    unzip
    plocate
    python
    nodejs
    npm
    just
    python-distro
    jujutsu
EOF

# System config
RUN <<EOF
    set -ex
    ln -sf /usr/bin/dash /usr/bin/sh
    sed 's/#Color/Color/' -i /etc/pacman.conf

EOF

run tee -a /etc/zsh/zshenv <<'EOF'
if [ -n "$ZDOTDIR" ] && [ ! -d "$ZDOTDIR" ] && [ -d "/run/host${ZDOTDIR}" ]; then
    export ZDOTDIR="/run/host${ZDOTDIR}"
fi
EOF

run tee -a /etc/environment <<'EOF'
TMUX_TMPDIR=/var/tmp
EOF

# Create build user
RUN useradd -m --shell=/bin/bash build && usermod -L build && \
    echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER build
WORKDIR /home/build

# Paru
RUN <<EOF
    set -ex
    git clone https://aur.archlinux.org/paru-bin.git
    cd paru-bin
    makepkg -si --noconfirm
EOF

RUN <<EOF
    paru -S --noconfirm
EOF

USER root

# Cleanup build user
RUN userdel -r build && \
    rm -drf /home/build && \
    sed -i '/build ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers && \
    sed -i '/root ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers && \
    rm -rf /home/build/.cache/* && \
    rm -rf \
        /tmp/* \
        /var/cache/pacman/pkg/*

# Link host tools
RUN /bin/bash <<EOF
    set -ex
    hosttools=(
        podman
        docker
        xdg-open
    )
    for tool in $hosttools; do
        ln -s /usr/bin/distrobox-host-exec /usr/local/bin/$tool
    done
EOF

ENV TMUX_TMPDIR=/var/tmp
