[user]
name = "Tobias Pisani"
email = "mail@topisani.dev"

[ui]
default-command = "log"
pager = ["sh", "-c", "diff-so-fancy | less -RFX"]

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "\n",
    indent("JJ:     ", diff.stat(72)),
  ),
  indent("JJ: ", diff.git())
)
'''

[template-aliases]
'format_short_signature(signature)' = 'signature'

[colors]
# Highlight hunks with background
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
# private-commits = "description(glob:'wip:*') | description(glob:'private:*')"

[snapshot]
auto-track = 'none()'
