#!/bin/bash

f="$1"
r="$2"
shift 2

sed -r ":1;/$f/I!b;s//\n&&&\n$r\n/;:2
    s/\n[[:lower:]](.*\n)(.)(.*\n)/\l\2\n\1\3/
    s/\n[^[:lower:]](.*\n)(.)(.*\n)/\u\2\n\1\3/;t2
    s/\n.*\n(.*)\n/\1/g;b1" "$@"
