#!/bin/bash

#export QT_QPA_PLATFORM=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORMTHEME=gtk2

~/dev/tablecloth/build/tablecloth/tablecloth -C ~/.config/tablecloth.ini &
CLOTH_PID=$!
sleep 2 
(cd ~/dev/tablecloth; ASAN_OPTIONS="new_delete_type_mismatch=0" build/cloth-notifications/cloth-notifications &)
battery_notifyd &
autorotation-daemon &
systemd-lock-handler cloth-lock &

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

sleep 1
dex --autostart &

wait $CLOTH_PID
