#!/bin/bash

#export QT_QPA_PLATFORM=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORMTHEME=gtk2
export QT_SCALE_FACTOR=1

# Use gtk theme for qt
export QT_QPA_PLATFORMTHEME="qt5ct"

# Use GTK3 for mullvad - See comments https://aur.archlinux.org/packages/mullvad
# Needed to fix a wxpython issue
export MULLVAD_USE_GTK3=yes


~/dev/tablecloth/build/tablecloth/tablecloth -C ~/.config/tablecloth.ini &
CLOTH_PID=$!
sleep 2 
(cd ~/dev/tablecloth; ASAN_OPTIONS="new_delete_type_mismatch=0" build/cloth-notifications/cloth-notifications &)
battery_notifyd &
autorotation-daemon &
systemd-lock-handler cloth-lock &

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

sleep 1
dex --autostart &

# Aarhus, Denmark
redshift -l 56:10 -m wayland &

wait $CLOTH_PID
