#!/bin/bash

# Config
WIDTH_PCT=70
HEIGHT_PCT=60


# Screen dimensions
DIMS=$(xrandr | grep \* | cut -d' ' -f4 | tail -n1)
WIDTH=$(echo "$DIMS" | cut -dx -f1)
HEIGHT=$(echo "$DIMS" | cut -dx -f2)

GEOMETRY=$((WIDTH * WIDTH_PCT / 100))x$((HEIGHT * HEIGHT_PCT / 100))+$(( (WIDTH - WIDTH * WIDTH_PCT / 100) / 2 ))

THIS_FILE=$0

# is_dropdown <window_id>
# Checks if window is the dropdown window
is_dropdown() {
	xprop -id $1 WM_WINDOW_ROLE | grep " = \"DropdownTerm\""
}

kill_dropdown() {
	wins=$(lsw -a)
	while read win; do
		is_dropdown $win && killw $win
	done <<< $wins &
}

open_dropdown() {
    args="$@"
    args="${args@Q}"
	termite --role=DropdownTerm --title=Dropdown --geometry=$GEOMETRY \
		--exec="sh -c '$THIS_FILE --setup $args'"
}

setup_term() {
    colorscheme-switch -t
    TERM=tmux-256color tmux attach -t Dropdown || tmux new-session -s Dropdown \; attach
}

if [[ "$1" == "--setup" ]]; then
    shift;
    setup_term "$@"
else
	if is_dropdown $(pfw); then
		killw $(pfw)
	else
		kill_dropdown
		open_dropdown
	fi
fi
