#!/bin/bash

_list_files() {
  for f in $(find "$1" -maxdepth 1 -type f -a -not -path './.git/*'); do
    if ! $(git check-ignore -q --no-index "$f"); then
      echo "$f" | sed 's|^\./||';
    fi
  done
}

_recurse_dir() {
  _list_files "$1"
  for dir in $(find "$1" -maxdepth 1 -type d -a -not -path './.git/*'); do
    if [[ "$dir" != "$1" ]]; then
      if ! $(git check-ignore -q --no-index "$dir"); then
        _recurse_dir "$dir";
      fi
    fi
  done
}

_recurse_dir "${1:-.}"
