#!/bin/bash

echo "Welcome back, have a nice day at work!"

#swaymsg output 'eDP-1' pos 0 806
#swaymsg output "'Dell Inc. DELL P2417H CW6Y77C712DL'" pos 1984 806
#swaymsg output "'Fujitsu Siemens Computers GmbH B22T-7 LED PG YV6J030129'" transform 90
#swaymsg output "'Fujitsu Siemens Computers GmbH B22T-7 LED PG YV6J030129'" pos 3930 465

get_eeids() {
  while read -r output hex conn; do
    [[ -z "$conn" ]] && conn=${output%%-*}
    echo "$output '$(xxd -r -p <<< "$hex")'"
  done < <(xrandr --prop | awk '
    !/^[ \t]/ {
        if (output && hex) print output, hex, conn
        output=$1
        hex=""
    }
    /ConnectorType:/ {conn=$2}
    /[:.]/ && h {
        sub(/.*000000fc00/, "", hex)
        hex = substr(hex, 0, 26) "0a"
        sub(/0a.*/, "", hex)
        h=0
    }
    h {sub(/[ \t]+/, ""); hex = hex $0}
    /EDID.*:/ {h=1}' | sort
  )
}

eeids="$(get_eeids)"

name_for_eeid() {
  disp_name=$1
  echo "$eeids" | grep -F "$disp_name" | cut -d" " -f1
}

for m in $(xrandr --query | grep "disconnected" | cut -d" " -f1); do
  xrandr --output $m --off
done

xrandr --output eDP1 --primary

xrandr \
  --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal \
  --output $(name_for_eeid "DELL P2417H")  --primary --mode 1920x1080 --pos 1997x0 --rotate normal

xrandr \
  --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal \
  --output $(name_for_eeid "DELL P2417H")  --primary --mode 1920x1080 --pos 1997x0 --rotate normal \
  --output $(name_for_eeid "B22T-7 LED PG") --mode 1920x1080 --pos 3996x0 --rotate right 
