#!/bin/bash

echo "Welcome back, have a nice day at work!"

swaymsg output 'eDP-1' pos 0 806
swaymsg output "'Dell Inc. DELL P2417H CW6Y77C712DL'" pos 1984 806
swaymsg output "'Fujitsu Siemens Computers GmbH B22T-7 LED PG YV6J030129'" transform 90
swaymsg output "'Fujitsu Siemens Computers GmbH B22T-7 LED PG YV6J030129'" pos 3930 465
