#!/usr/bin/env bash
 
# toggle_gaps [on|off|toggle]
 
INNER=15
OUTER=0
 
mode=$1
 
if [[ -z "$mode" || "$mode" == "toggle" ]]; then
 
    # Get current workspace.
    workspace=$(swaymsg -t get_workspaces \
            | jq -r '.[] | if .focused then .id else empty end')
    # Get current inner gap size. (0 means default)
    inner_gaps=$(swaymsg -t get_tree \
            | jq -r 'recurse(.nodes[]; .nodes != null) | if .id == "'"$workspace"'" then .gaps.inner else empty end')
 
    if [[   "$inner_gaps" == 0 ]]; then
        mode="on"
    else
        mode="off"
    fi
fi
 
if [[ "$mode" == "on" ]]; then
    swaymsg "gaps inner current set $INNER; gaps outer current set $OUTER"
else
    swaymsg "gaps inner current set 0; gaps outer current set 0"
fi
