#!/bin/bash

sxhkd -c ~/.config/bspwm/sxhkdrc &

xsetroot -cursor_name left_ptr &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
desktops=( 1 2 3 4 5 6 7 8 9 0 )
for m in $(xrandr --query | grep " connected" | sed '/eDP1/d' - | cut -d" " -f1); do
  bspc monitor $m -d ${desktops[-1]}
  unset 'desktops[${#desktops[@]}-1]'
done
bspc monitor eDP1 -d ${desktops[@]}

bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_border_color "#178ca6"
bspc config normal_border_color "#23262a"
bspc rule -a google-chrome desktop='1' follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Screenkey manage=off

# $HOME/.config/polybar/launch.sh
# ~/.fehbg
# mpd &
dunst &
picom &
killall polybar
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m polybar -r -c .config/bspwm/polybar main &
done
xss-lock --transfer-sleep-lock -- betterlockscreen -l --nofork &
betterlockscreen -w &
