#!/bin/bash

init='{
  "cache": {
    "directory": "'$HOME'/.cache/ccls/",
    "format": "binary"
  },
  "highlight": {
    "lsRanges": true
  },
  "completion": {
    "detailedLabel": false
  },
  "index": {
    "comments": 1,
    "trackDependency": 2,
    "threads": 4,
    "multiVersion": 0,
    "multiVersionBlacklist": ["^/usr/include"],
    "onChange": false
  }
}'

ccls --init="$init" -log-file=/tmp/ccls.log "$@"
