[preferred]
default=luminous;gtk;gnome;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
# org.freedesktop.impl.portal.Secret=gnome-keyring;
org.freedesktop.impl.portal.ScreenCast=luminous;gnome;
# org.freedesktop.impl.portal.ScreenCast=gnome;
org.freedesktop.impl.portal.FileChooser=luminous;gnome;
