[preferred]
default=luminous;gtk;gnome;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
<<<<<<< Updated upstream
org.freedesktop.impl.portal.Secret=gnome-keyring;
org.freedesktop.impl.portal.ScreenCast=luminous;gnome;
||||||| Stash base
# org.freedesktop.impl.portal.Secret=gnome-keyring;
org.freedesktop.impl.portal.ScreenCast=luminous;gnome;
=======
# org.freedesktop.impl.portal.Secret=gnome-keyring;
org.freedesktop.impl.portal.ScreenCast=gnome;
>>>>>>> Stashed changes
# org.freedesktop.impl.portal.ScreenCast=gnome;
<<<<<<< Updated upstream
org.freedesktop.impl.portal.FileChooser=luminous;gnome;gtk;
org.freedesktop.impl.portal.AppChooser=gtk
org.freedesktop.impl.portal.Settings=gtk
||||||| Stash base
org.freedesktop.impl.portal.FileChooser=luminous;gnome;
=======
org.freedesktop.impl.portal.FileChooser=gnome;gtk
>>>>>>> Stashed changes
