#!/bin/bash

# Generate flatblue theme.

alpha() {
  echo -n "$1" | sed "s/rgb:\\(.*\\)/rgba:\\1$2/"
}

sed 's/, */,/g;s/ *+/+/' <<EOF
# Markdown highlighting
face global title                       $green,                default       +b
face global header                      $blue_light,                 default       +b
face global bold                        $fg,                   default       +b
face global italic                      $fg3,                  default       +i
face global mono                        $fg3,                  default
face global block                       $fg2,                  default
face global link                        $blue,                 default
face global bullet                      $purple,               default
face global list                        $purple,               default

face global Reference                   $fg,               default       +b
face global PrimarySelection            default,           $(alpha $blue_light 30)
face global SecondarySelection          default,           $(alpha $blue 30)
face global PrimaryCursor               $bg0,              $(alpha $bluish_fg e0)
face global SecondaryCursor             $bg0,              $(alpha $bluish_fg 80)
face global PrimaryCursorEol            $bg0,              $fg0      +f
face global SecondaryCursorEol          $bg3,              $fg3      +f
face global LineNumbers                 $bg4,              default
face global LineNumberCursor            $fg3,              $bg2
face global LineNumbersWrapped          $bg,               default
face global MenuForeground              $bg1,              $blue
face global MenuBackground              $fg,               $bg1
face global MenuInfo                    $blue_light,       $bg1
face global Error                       $red,              default
face global StatusLine                  $fg,               default
face global StatusLineMode              $bg,               $yellow,       +b
face global StatusLineInfo              $purple,           default
face global StatusLineValue             $red,              default
face global StatusCursor                $bg,               $fg
face global Prompt                      $yellow,           default
face global MatchingChar                                                '+b'
face global BufferPadding               $bg2,              default
face global Whitespace                  $bg1,              default      +f
face global WhitespaceIndent            $bg2,              default      +f
face global Information                 $blue,             $float_bg

face global GitBlame                    $fg2,              default

# Code highlighting
face global value                       $purple,           default
face global type                        $blue_light,       default
face global variable                    $aqua_dark,        default
face global module                      $orange,           default
face global function                    $yellow_light,     default
face global string                      $green,            default
face global documentation               $green,            default
face global keyword                     $red,              default
face global operator                    $fg,               default       +d
face global attribute                   $red,              default
face global meta                        $orange,           default
face global builtin                     $purple,           default
face global comment                     $gray,             default       +i
face global identifier                  $yellow_dark,      default
face global annotation                  $gray,             default

face global DiagnosticWarning           default, default,  $yellow       +ca
face global DiagnosticError             default, default,  $red          +ca
face global DiagnosticInfo              default, default,  $green        +ca
face global DiagnosticHint              default, default,  $gray         +ca
face global LineFlagError               $red,              default       +b
face global LineFlagWarning             $yellow,           default       +b
face global LineFlagInfo                $green,            default       +b
face global LineFlagHint                $gray,             default       +b

face global Reference                                                    '+b'
face global ReferenceBind                                                '+bu'

# Plugs
face global Phantom                     $bg,               $green_dark
face global Search                      $fg,               $bg3
face global PrimarySelectionDefault     $fg,               $blue
face global PrimarySelectionSearch      $fg,               $blue
face global SearchBackground            $gray,             default
face global SearchOccurrence            $fg,               default        +ib

face global SnippetsOtherPlaceholders   default,           $(alpha $green 20)
face global SnippetsNextPlaceholders    default,           $(alpha $green 40)

# kakoune-focus
face global FocusMarker                 $bg3,                             +fa

# Lsp
face global InlayHint                 $blue_dark+iF

face global memberFunction            '+i@function'
face global cppConcept                '+i@type'
face global memberVariable            '+i@variable'
face global cppMacro                  $purple_light,  default
face global cppDependent              $aqua,          default
face global disabledRegion            $gray,          default

# LSP Info box
face global InfoDefault               Information
face global InfoBlock                 InfoDefault
face global InfoBlockQuote            ,+i@InfoDefault
face global InfoBullet                InfoDefault
face global InfoHeader                ,+b@InfoDefault
face global InfoLink                  ,+i@InfoDefault
face global InfoLinkMono              InfoDefault
face global InfoMono                  $gray@InfoDefault
face global InfoRule                  $gray@InfoDefault
face global InfoDiagnosticError       $red@InfoDefault
face global InfoDiagnosticHint        $purple_dark@InfoDefault
face global InfoDiagnosticInformation $green@InfoDefault
face global InfoDiagnosticWarning     $yellow@InfoDefault

face global InlayDiagnosticWarning           $yellow       +dfa
face global InlayDiagnosticError             $red          +dfa
face global InlayDiagnosticInfo              $green        +dfa
face global InlayDiagnosticHint              $purple_dark  +fa

face global StatusLspWarning           $yellow            +fa
face global StatusLspError             $red               +fa
face global StatusLspInfo              $green             +fa
face global StatusLspHint              $purple_dark       +fa

decl str lsp_diagnostic_line_error_sign
decl str lsp_diagnostic_line_warning_sign
decl str lsp_diagnostic_line_info_sign
decl str lsp_diagnostic_line_hint_sign
set global lsp_diagnostic_line_error_sign '●'
set global lsp_diagnostic_line_warning_sign '●'
set global lsp_diagnostic_line_info_sign '●'
set global lsp_diagnostic_line_hint_sign '●'
# set global lsp_diagnostic_line_error_sign ' '
# set global lsp_diagnostic_line_warning_sign ' '
# set global lsp_diagnostic_line_info_sign ' '
# set global lsp_diagnostic_line_hint_sign ' '
set -add global ui_options 'terminal_padding_char= '

set global git_diff_add_char "{$green}▎"
set global git_diff_mod_char "{$blue}▎"
set global git_diff_del_char "{$red}🬼"
set global git_diff_top_char "{$red}🭗"

set-face global GitBlameLineRef     $yellow,$bg2
set-face global GitBlameLineSummary $green,$bg2
set-face global GitBlameLineAuthor  $blue_light,$bg2
set-face global GitBlameLineTime    default,$bg2@comment

# Todo Highlights
face global MarkerTodo    $yellow+b
face global MarkerNote    $blue_light+b
face global MarkerFixme   $purple_light+b


# Switch cursor color in insert mode
face global PrimaryCursorNormal              $bg0,              $(alpha $bluish_fg e0)
face global PrimaryCursorEolNormal           $bg0,              $fg0      +f

face global PrimaryCursorInsert              $bg0,              $(alpha $yellow e0)
face global PrimaryCursorEolInsert           PrimaryCursorInsert

face global PrimaryCursorEol                 PrimaryCursorEolNormal
face global PrimaryCursor                    PrimaryCursorNormal

face global StatusLineMode                $blue_light,           default       +b

face global DefaultFocused $fg,$bg
face global DefaultUnfocused $fg,$bg_unfocused
face global Default DefaultFocused

rmhooks global flatblue

hook -group flatblue global ModeChange (push|pop):.*insert %{
  face window PrimaryCursor PrimaryCursorInsert
  face window PrimaryCursorEol PrimaryCursorEolInsert
  face window StatusLineMode              $yellow,           default       +b
  
  # add-highlighter window/current-line line '%val{cursor_line}' ',$bg3'
}

hook -group flatblue global ModeChange (push|pop):.*insert.+ %{
  set-face window PrimaryCursor PrimaryCursorNormal
  set-face window PrimaryCursorEol PrimaryCursorEolNormal
  face window StatusLineMode              $blue_light,           default       +b
  
  # remove-highlighter window/current-line
}

hook -group flatblue global FocusIn .* %{
  face window Default DefaultFocused
}

hook -group flatblue global FocusOut .* %{
  face window Default DefaultUnfocused
}


# kak-tree-sitter

# set-face global ts_unknown                      "$bg,$red+ub"
set-face global ts_unknown                      ""
set-face global ts_attribute                    "variable"
set-face global ts_comment                      "comment"
set-face global ts_comment_documentation        "documentation"
set-face global ts_comment_block                "ts_comment"
set-face global ts_comment_line                 "ts_comment"
set-face global ts_conceal                      "+i@keyword"
set-face global ts_constant                     "variable"
set-face global ts_constant_builtin             "builtin"
set-face global ts_constant_builtin_boolean     "builtin"
set-face global ts_constant_character           "value"
set-face global ts_constant_character_escape    "$yellow_dark"
set-face global ts_constant_macro               "cppMacro"
set-face global ts_constant_numeric             "value"
set-face global ts_constant_numeric_float       "ts_constant_numeric"
set-face global ts_constant_numeric_integer     "ts_constant_numeric"
set-face global ts_constructor                  "function"
set-face global ts_diff_plus                    "$green"
set-face global ts_diff_minus                   "$red"
set-face global ts_diff_delta                   "$blue"
set-face global ts_diff_delta_moved             "$blue_light"
set-face global ts_error                        "error"
set-face global ts_function                     "function"
set-face global ts_function_builtin             "function"
set-face global ts_function_macro               "cppMacro"
set-face global ts_function_method              "+i@ts_function"
set-face global ts_function_special             "+i@ts_function"
set-face global ts_hint                         "MarkerTodo"
set-face global ts_info                         "MarkerNote"
set-face global ts_keyword                      "keyword"
set-face global ts_keyword_control              "ts_keyword"
set-face global ts_keyword_conditional          "+i@keyword"
set-face global ts_keyword_control_conditional  "+i@keyword"
set-face global ts_keyword_control_directive    "+i@keyword"
set-face global ts_keyword_control_import       "+i@keyword"
set-face global ts_keyword_control_repeat       "ts_keyword"
set-face global ts_keyword_control_return       "ts_keyword"
set-face global ts_keyword_control_except       "ts_keyword"
set-face global ts_keyword_control_exception    "ts_keyword"
set-face global ts_keyword_directive            "$orange+i"
set-face global ts_keyword_function             "ts_keyword"
set-face global ts_keyword_operator             "ts_keyword"
set-face global ts_keyword_special              "ts_keyword" 
set-face global ts_keyword_storage              "ts_keyword" 
set-face global ts_keyword_storage_modifier     "ts_keyword" 
set-face global ts_keyword_storage_modifier_mut "ts_keyword" 
set-face global ts_keyword_storage_modifier_ref "operator" 
set-face global ts_keyword_storage_type         "ts_keyword" 
set-face global ts_label                        "$orange+i"
set-face global ts_markup_bold                  "bold"
set-face global ts_markup_heading               "header"
set-face global ts_markup_heading_1             "title"
set-face global ts_markup_heading_2             "header"
set-face global ts_markup_heading_3             "+i@header"
set-face global ts_markup_heading_4             "+i@header"
set-face global ts_markup_heading_5             "+i@header"
set-face global ts_markup_heading_6             "+i@header"
set-face global ts_markup_heading_marker        "comment"
set-face global ts_markup_italic                "italic"
set-face global ts_markup_list_checked          "$green"
set-face global ts_markup_list_numbered         "list"
set-face global ts_markup_list_unchecked        "list"
set-face global ts_markup_list_unnumbered       "bullet"
set-face global ts_markup_link_label            "$green_dark+b"
set-face global ts_markup_link_url              "$aqua_dark+u"
set-face global ts_markup_link_uri              "$aqua_dark+u"
set-face global ts_markup_link_text             "$green_dark+b"
set-face global ts_markup_quote                 "block"
set-face global ts_markup_raw                   "mono"
set-face global ts_markup_raw_block             "mono"
set-face global ts_markup_raw_inline            "$fg3,$bg3"
set-face global ts_markup_strikethrough         "+s@comment"
set-face global ts_namespace                    "module"
set-face global ts_operator                     "operator"
set-face global ts_property                     "variable"
set-face global ts_punctuation                  "operator"
set-face global ts_punctuation_bracket          "ts_punctuation"
set-face global ts_punctuation_delimiter        "ts_punctuation"
set-face global ts_punctuation_special          "ts_punctuation"
set-face global ts_special                      "cppMacro"
set-face global ts_spell                        "error"
set-face global ts_string                       "string"
set-face global ts_string_regex                 "$yellow_dark"
set-face global ts_string_regexp                "$yellow_dark"
set-face global ts_string_escape                "$orange"
set-face global ts_string_special               "$blue"
set-face global ts_string_special_path          "$orange"
set-face global ts_string_special_symbol        "$orange"
set-face global ts_string_symbol                "$purple_light"
set-face global ts_tag                          "$red"
set-face global ts_tag_error                    "error"
set-face global ts_text                         "default"
set-face global ts_text_title                   "title"
set-face global ts_type                         "type"
set-face global ts_type_builtin                 "ts_type"
set-face global ts_type_enum_variant            "variable"
set-face global ts_variable                     "variable"
set-face global ts_variable_builtin             "builtin"
set-face global ts_variable_other_member        "+i@variable"
set-face global ts_variable_parameter           "$aqua"
set-face global ts_warning                      "$orange+b"

set-face global ts_punctuation_special_link     "$bg3"
set-face global ts_punctuation_bracket_link     "$bg3"
set-face global ts_markup_link_url_image        "$purple+u"

set-face global JumpLabel                       "$bg0,$purple_dark+bdF"

# kak-tree-sitter-highlight-submit-faces
EOF
