#!/bin/bash
cquery --init="{
  \"cacheDirectory\": \"$HOME/.cache/cquery/\",
  \"cacheFormat\": \"msgpack\",
  \"completion\": {
    \"detailedLabel\": true
  },
  \"xref\": {
    \"container\": true
  }
}"
