#!/bin/bash

cur=$(xfconf-query -c xfce4-panel -p /panels/panel-0/autohide-behavior)
if [[ cur -eq 0 ]]; then
  nxt=2
  fluxbox-remote "MacroCmd {SetResourceValue session.screen0.toolbar.visible false} {Reconfigure}"
else
  nxt=0
  fluxbox-remote "MacroCmd {SetResourceValue session.screen0.toolbar.visible true} {Reconfigure}"
fi
xfconf-query -c xfce4-panel -p /panels/panel-0/autohide-behavior -s $nxt
