[plugin]
prepend_previewers = [
  { mime = "text/csv", run = "miller"},
  { name = "*.md", run = "glow" },
]
append_previewers = [
  { name = "*", run = "hexyl" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[opener]
open = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Open", for = "unix" }, # add orphan = true
]
